blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://discord.com/invite/jHunPNdphj
    about: Questions about the game should be asked in the Discord, not in the issue tracker. 
